### ISSUE TITLE
Seems to be substituting "-" for "+" in result of toBase64

### ISSUE THREAD

**Issue by DrPaulBrewer** [tjmehta/hex64#1]
I understand this is old code, and I don't really need a response.  Furthermore, my issue got fixed by using different modules (`npm:hasha` allows a choice of encodings).  I'm posting this information in case it is helpful.

Tried to use `hex64.toBase64` to convert some md5 hashes that were returned in hex from `npm:md5-file/promise`  so I could compare them
to a base64 md5 produced by `npm:md5-base64` elsewhere

In the below output, "expected" was produced by calling `npm:md5-base64` on the string that was written to a file.

The file was later read and a hex md5 calculated with `npm:md5-file/promise` and that hex was converted to base64 by `hex64.toBase64`.  They don't match, but are only one character off. The "+" produced in md5-base64 "expected" has become a "-" in the hex->base64 "actual".

> file: code.js expected: RjK5k+i1bhRSSR9wBwwzCA== actual: RjK5k-i1bhRSSR9wBwwzCA==
> file: hello.txt expected: 3WuLuH52gdu+qw1QWL34dA== actual: 3WuLuH52gdu-qw1QWL34dA==
>

**Comment by tjmehta** [comment]
Hello Dr Brewer,

This is intentional, as I intended to use base64 encoded string in urls (see wiki 'base64url' https://en.m.wikipedia.org/wiki/Base64). If you check out the source I am intentionally replacing + and / in base64 encoded string to - and _.

Thanks for writing this issue! I will make sure to add a note in the readme about this implementation decision.

**Comment by DrPaulBrewer** [comment]
Thanks for the response.
